.modal-container.slds-modal__container {
  width: calc(100% - 2rem) !important;
  min-width: calc(100% - 6rem) !important;
  max-width: calc(100% - 6rem) !important;
  position: absolute !important;
  top: 3rem !important;
  left: 3rem !important;
}
.modal-footer.slds-modal__footer {
  display: none !important;
}
.modal-header.slds-modal__header {
  position: absolute !important;
  top: 0 !important;
  right: 0 !important;
}